## 错误处理

### try-catch 语句

应该把可能发生错误的代码放在 try-catch 语句中，把用于错误处理的代码放在 catch 语句中。

    try {
        // 可能会出错的代码
    } catch (error) {
        // 错误发生时如何处理
    }

try  块中任何代码发生错误会立即退出代码执行过程，接着执行 catch 块。此时，catch 块会接收到一个包含 name（错误类型）和 message（错误消息）属性错误对象：

    try {
        // ...
    } catch (error) {
        alert(error.name, error.message);
    }

#### finally 子句

可选，不管是否发生错误，始终都会执行。

如果提供 finally 子句，则 catch 子句就成了可选的（catch 或 finally 有一个即可）。

兼容性：

 IE7 及更早版本中有一个 bug：除非有 catch 子句，否则 finally 中的代码永远不会执行。如果你仍然要考虑 IE 的早期版本，那就只好提供一个 catch 子句，哪怕里面什么都不写。 IE8 修复了这个 bug。

 #### 错误类型

执行代码期间可能会发生的错误有多种类型。每种错误都有对应的错误类型，而当错误发生时，就会抛出相应类型的错误对象。 ECMA-262 定义了下列 7 种错误类型：

- Error：是基类型，其他错误类型都继承自该类型。这个基类型的主要目的是供开发人员抛出自定义错误；
- ReferenceError：在访问不存在的变量时，就会发生这种错误：var obj = x; // x 未声明
- TypeError：在执行特定于类型的操作时，变量的类型并不符合要求所致。var o = new 10; //抛出 TypeError；alert("name" in true); //抛出 TypeError；
- SyntaxError：语法错误；
- RangeError：会在数值超出相应范围时触发：var items1 = new Array(-20);var items2 = new Array(Number.MAX_VALUE);
- EvalError：没有把 eval()当成函数调用，就会抛出错误：new eval(); eval = foo;
- URIError：在使用 encodeURI()或 decodeURI()，而 URI 格式不正确时，就会导致 URIError 错误；

### 抛出错误

throw 操作符，主动抛出错误。任何类型都可以作为值。

    throw 12345;
    throw "Hello world!";
    throw true;
    throw { name: "JavaScript"};

遇到 throw 操作符时，代码立即停止执行。知道遇到 try-catch 语句捕获到抛出的值时，代码才继续执行。

通过抛出内置的错误类型，可以更真实的模拟浏览器错误。每种错误类型的构造函数接受一个参数，即实际的错误信息 message：

    throw new Error("Something bad happened.");

    throw new SyntaxError("I don’t like your syntax.");
    throw new TypeError("What type of variable do you take me for?");
    throw new RangeError("Sorry, you just don’t have the range.");
    throw new EvalError("That doesn’t evaluate.");
    throw new URIError("Uri, is that you?");
    throw new ReferenceError("You didn’t cite your references properly.");

#### 自定义错误

利用原型链继承 Error 对象，可以创建自定义错误类型：

    function CustomError(message){
        this.name = "CustomError";
        this.message = message;
    }
    CustomError.prototype = new Error();

    throw new CustomError("My message");

#### 抛出错误的时机

准确描述错误信息，对错误处理有帮助：

    if (!(values instanceof Array)){
        throw new Error("process(): Argument must be an array.");
    }

### 错误事件

任何没有被 try-catch 语句捕获的错误都对触发 window 对象的 error 事件。

任何浏览器都不会为 onerror 事件处理程序创建 event 对象，它可以接收三个参数：错误消息、错误所在的 URL 和行号。

要指定 onerror 事件处理程序，必须使用如下所示的 DOM0 级技术，它没有遵循“ DOM2 级事件”的标准格式：

    window.onerror = function(message, url, line) {
        alert(message);
    };

在事件处理程序中返回false，可以阻止浏览器报告错误的默认行为：

    window.onerror = function(message, url, line){
        alert(message);
        return false;
    };

图像也支持 error 事件，图像的 src 特性中的 URL 不能返回可以被识别的图像格式，就会触发 error 事件。此时的 error 事件遵循 DOM 格式，会返回一个以图像为目标的 event 对象：

    var image = new Image();
    
    EventUtil.addHandler(image, "load", function(event){
        alert("Image loaded!");
    });
    
    EventUtil.addHandler(image, "error", function(event){
        alert("Image not loaded!");
    });
    
    image.src = "smilex.gif"; //指定不存在的文件

### 常见的错误类型



